spring:
  application:
    name: reading-service
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-summer-scene-a1di24n8-pooler.ap-southeast-1.aws.neon.tech:5432/reading_service?sslmode=require
    username: neondb_owner
    password: npg_1qJYk3avVWKE

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 9000
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


