spring:
  application:
    name: reading-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity.sep.local/realms/SEP490
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-summer-scene-a1di24n8-pooler.ap-southeast-1.aws.neon.tech:5432/reading_service?sslmode=require
    username: neondb_owner
    password: npg_1qJYk3avVWKE

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 9000
  servlet:
    context-path: /reading
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


keycloak:
  base-uri: http://identity.sep.local
  token-uri: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token
  realm: SEP490
  client-id: fptu_sep490
  client-secret: csJfV0ielwCWBYKYzUZnQTTW25nkIKk2
  scope: openid
  redirect-uri: http://identity.sep.local/realms/SEP490/broker/google/endpoint

springdoc:
  paths-to-match: /**
  packages-to-scan: com.fptu.sep490.readingservice.controller
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauth-flow:
    authorization-url: http://identity.sep.local/realms/SEP490/protocol/openid-connect/auth
    token-url: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token


