spring:
  application:
    name: reading-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity.sep.local/realms/SEP490

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.91.12.100:5432/reading_service
    username: phucth
    password: 123afd4a_sfd
    hikari:
      data-source-properties:
        prepareThreshold: 0
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000


  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 9000
  servlet:
    context-path: /reading
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


keycloak:
  base-uri: http://identity.sep.local
  token-uri: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token
  realm: SEP490
  client-id: fptu_sep490
  client-secret: LA7hBoWpOK58zJY2hKlPUcgweTTtWiIT
  scope: openid
  redirect-uri: http://identity.sep.local/realms/SEP490/broker/google/endpoint

springdoc:
  paths-to-match: /**
  packages-to-scan: com.fptu.sep490.readingservice.controller
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauth-flow:
    authorization-url: http://identity.sep.local/realms/SEP490/protocol/openid-connect/auth
    token-url: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token

service:
  personal-service: http://localhost:8072/personal

kafka:
  topic:
    streak: streak-topic
    topic-master: topic-master