spring:
  profiles:
    active: local
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8082
  servlet:
    context-path: /notification

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: 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

springdoc:
  paths-to-match: /**
  packages-to-scan: com.fptu.sep490.identityservice.controller
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauth-flow:
    authorization-url: http://identity:8080/realms/SEP490/protocol/openid-connect/auth
    token-url: http://identity:8080/realms/SEP490/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

kafka:
  topic:
    user-verification: user-verification-topic
