version: "3.9"

services:
  nginx:
    container_name: nginx
    image:  nginx:1.27.2
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    ports:
      - "80:80"
    networks:
      - sep-network

  identity:
    container_name: identity
    image: quay.io/keycloak/keycloak:26.0.2
    command: 'start-dev --features=scripts --import-realm'
    environment:
      KC_FEATURES: scripts
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ep-old-credit-a1p3nce6-pooler.ap-southeast-1.aws.neon.tech:5432/keycloak?sslmode=require
      KC_DB_USERNAME: neondb_owner
      KC_DB_PASSWORD: npg_ovK4lmXJuTr7
      KC_HTTP_PORT: 80
      KC_HTTP_ENABLED: "true"
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./identity/themes/sep/theme:/opt/keycloak/themes
      - keycloak_data:/var/lib/keycloak/data
    networks:
      - sep-network





  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: ${KAFKA_SERVICE_HOST}
    ports:
      - ${KAFKA_SERVICE_PORT}:${KAFKA_SERVICE_PORT}
      - "9093:9093"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - sep-network
  redis:
    container_name: redis
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST:-redis}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT:-6379}
    volumes:
      - redis:/data
    networks:
      - sep-network




volumes:
  postgres:
    driver: local
  redis:
    driver: local
  keycloak_data:
    driver: local

networks:
  sep-network:
    driver: bridge