logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
management:
  endpoints:
    web:
      expose:
        include: '*'

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: IDENTITY-SERVICE
          uri: http://47.128.245.17:8090
          predicates:
            - Path=/identity/api/v1/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - name: identity-service
        url: http://47.128.245.17:8090/identity/v3/api-docs


server:
  port: 9191