logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
management:
  endpoints:
    web:
      expose:
        include: '*'

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/identity/**
          filters:
              - StripPrefix=2
        - id: reading-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/reading/**
          filters:
            - StripPrefix=2
        - id: file-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/resource/**
          filters:
            - StripPrefix=2

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://ielts-mate-fe.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - name: identity-service
        url: http://localhost:9191/api/v1/identity/v3/api-docs
      - name: reading-service
        url: http://localhost:9191/api/v1/reading/v3/api-docs
      - name: file-service
        url: http://localhost:9191/api/v1/resource/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9191