logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
management:
  endpoints:
    web:
      expose:
        include: '*'
server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id : notification-sse
          uri: ${NOTIFICATION_API}
          predicates:
            - Path=/api/v1/notification/sse/stream/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Cache-Control,no-cache
            - SetResponseHeader=Content-Type,text/event-stream;charset=UTF-8
            - AddResponseHeader=Connection,keep-alive
            - AddResponseHeader=X-Accel-Buffering,no

        - id: identity-service
          uri: ${IDENTITY_API}
          predicates:
            - Path=/api/v1/identity/**
          filters:
            - StripPrefix=2

        - id: reading-service
          uri: ${READING_API}
          predicates:
            - Path=/api/v1/reading/**
          filters:
            - StripPrefix=2

        - id: file-service
          uri: ${FILE_API}
          predicates:
            - Path=/api/v1/resource/**
          filters:
            - StripPrefix=2

        - id: listening-service
          uri: ${LISTENING_API}
          predicates:
            - Path=/api/v1/listening/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: ${NOTIFICATION_API}
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=2

        - id: personal-service
          uri: ${PERSONAL_API}
          predicates:
            - Path=/api/v1/personal/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://ielts-mate-fe.vercel.app"
              - "https://tootsstore.online"
              - "http://3.236.168.139"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 10000
        response-timeout: 3600s
        pool:
          max-idle-time: 3600s
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE}
    fetch-registry: true
    register-with-eureka: true



