logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
management:
  endpoints:
    web:
      expose:
        include: '*'

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: notification-sse
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/notification/sse/stream/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Cache-Control,no-cache
            - SetResponseHeader=Content-Type,text/event-stream;charset=UTF-8
            - AddResponseHeader=Connection,keep-alive
            - AddResponseHeader=X-Accel-Buffering,no

        - id: identity-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/identity/**
          filters:
              - StripPrefix=2
        - id: reading-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/reading/**
          filters:
            - StripPrefix=2
        - id: file-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/resource/**
          filters:
            - StripPrefix=2
        - id: listening-service
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/listening/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=2
        - id: personal-service
          uri: http://localhost:8072
          predicates:
            - Path=/api/v1/personal/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://ielts-mate-fe.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 10000
        response-timeout: 3600s
        pool:
          max-idle-time: 3600s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - name: identity-service
        url: http://localhost:9191/api/v1/identity/v3/api-docs
      - name: reading-service
        url: http://localhost:9191/api/v1/reading/v3/api-docs
      - name: file-service
        url: http://localhost:9191/api/v1/resource/v3/api-docs
      - name: listening-service
        url: http://localhost:9191/api/v1/listening/v3/api-docs
      - name: notification-service
        url: http://localhost:9191/api/v1/notification/v3/api-docs
      - name: personal-service
        url: http://localhost:9191/api/v1/personal/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true
server:
  port: 9191