spring:
  application:
    name: listening-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.request.size: 10485760
    consumer:
      group-id: listening-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity.sep.local/realms/SEP490
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-old-credit-a1p3nce6-pooler.ap-southeast-1.aws.neon.tech:5432/listening_service?sslmode=require&prepareThreshold=0
    username: neondb_owner
    password: npg_ovK4lmXJuTr7
    hikari:
      data-source-properties:
        prepareThreshold: 0

server:
  port: 8071
  servlet:
    context-path: /listening


logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

keycloak:
  base-uri: http://identity.sep.local
  token-uri: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token
  realm: SEP490
  client-id: fptu_sep490
  client-secret: WUMhVFCbRrTmy3BwcLEdHsZ50Hau9Gjl
  scope: openid
  redirect-uri: http://identity.sep.local/realms/SEP490/broker/google/endpoint

springdoc:
  paths-to-match: /**
  packages-to-scan: com.fptu.sep490.listeningservice.controller
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauth-flow:
    authorization-url: http://identity.sep.local/realms/SEP490/protocol/openid-connect/auth
    token-url: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token

topic:
  upload-audio: upload-audio-topic
  update-listening-audio: update-listening-audio-topic
  send-notification: send-notification-topic


cloudinary:
  cloud-name: dbrm5eowo
  api-key: 566182576423582
  api-secret: mYJD0DbR4oXl4oD8g22RtvJx9kU
