server:
  servlet:
    context-path: /resource
  port: 8070

spring:
  application:
    name: file-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity.sep.local/realms/SEP490

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-divine-credit-a1g68jhj-pooler.ap-southeast-1.aws.neon.tech:5432/file-service?sslmode=require&prepareThreshold=0
    username: neondb_owner
    password: npg_9abzQo8sNRpq
    hikari:
      data-source-properties:
        prepareThreshold: 0

keycloak:
  base-uri: http://identity.sep.local
  token-uri: http://identity.sep.local/realms/SEP490/protocol/openid-connect/token
  realm: SEP490
  client-id: fptu_sep490
  client-secret: Y6mBJ0SUomyVdgf7XiKZLgH71n7m5V6P
  scope: openid
  redirect-uri: http://identity.sep.local/realms/SEP490/broker/google/endpoint

springdoc:
  paths-to-match: /**
  packages-to-scan: com.fptu.sep490.fileservice.controller
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauth-flow:
    authorization-url: http://localhost:8080/realms/SEP490/protocol/openid-connect/auth
    token-url: http://localhost:8080/realms/SEP490/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: dbrm5eowo
  api-key: 566182576423582
  api-secret: mYJD0DbR4oXl4oD8g22RtvJx9kU