spring:
  application:
    name: common-library
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER}

cors:
  allowed-origins: '*'
  allowed-methods: '*'
  allowed-headers: '*'

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

keycloak:
  token-uri: ${KEYCLOAK_SERVICE}/realms/SEP490/protocol/openid-connect/token
  scope: openid
