name: Ielts Mate Backend

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & Up containers
        run: docker compose -f docker-compose.yml up -d --build

